In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data='Food_Data_Africa.csv'
df=pd.read_csv(data,encoding='latin-1')
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
5,4,Algeria,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,2932.00,2958.00,2941.00,2921.00,2932.00
6,4,Algeria,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,67.14,67.38,67.37,66.11,67.10
7,4,Algeria,2903,Vegetal Products,684,Fat supply quantity (g/capita/day),g/capita/day,53.84,54.72,52.04,55.59,54.57
8,4,Algeria,2941,Animal Products,664,Food supply (kcal/capita/day),kcal/capita/day,444.00,421.00,431.00,421.00,390.00
9,4,Algeria,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,27.76,26.97,27.35,26.71,24.73
10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,26.22,24.64,25.37,24.60,22.71
11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
12,4,Algeria,2905,Cereals - Excluding Beer,5611,Import Quantity,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
13,4,Algeria,2905,Cereals - Excluding Beer,5072,Stock Variation,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
14,4,Algeria,2905,Cereals - Excluding Beer,5911,Export Quantity,1000 tonnes,3.00,7.00,7.00,10.00,17.00
15,4,Algeria,2905,Cereals - Excluding Beer,5301,Domestic supply quantity,1000 tonnes,15353.00,16075.00,16056.00,15803.00,17004.00
16,4,Algeria,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
17,4,Algeria,2905,Cereals - Excluding Beer,5527,Seed,1000 tonnes,177.00,189.00,197.00,202.00,278.00
18,4,Algeria,2905,Cereals - Excluding Beer,5123,Losses,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
19,4,Algeria,2905,Cereals - Excluding Beer,5131,Processing,1000 tonnes,35.00,38.00,37.00,33.00,44.00
20,4,Algeria,2905,Cereals - Excluding Beer,5154,Other uses (non-food),1000 tonnes,787.00,847.00,835.00,840.00,951.00
21,4,Algeria,2905,Cereals - Excluding Beer,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,-8.00
22,4,Algeria,2905,Cereals - Excluding Beer,5142,Food,1000 tonnes,8546.00,8729.00,9001.00,8941.00,9219.00
23,4,Algeria,2905,Cereals - Excluding Beer,645,Food supply quantity (kg/capita/yr),kg,219.56,219.72,221.98,216.02,218.31
24,4,Algeria,2905,Cereals - Excluding Beer,664,Food supply (kcal/capita/day),kcal/capita/day,1680.00,1682.00,1699.00,1656.00,1672.00
25,4,Algeria,2905,Cereals - Excluding Beer,674,Protein supply quantity (g/capita/day),g/capita/day,49.43,49.54,50.01,48.86,49.36
26,4,Algeria,2905,Cereals - Excluding Beer,684,Fat supply quantity (g/capita/day),g/capita/day,6.84,6.78,6.83,6.63,6.58
27,4,Algeria,2511,Wheat and products,5511,Production,1000 tonnes,2436.00,2657.00,2440.00,2437.00,3981.00
28,4,Algeria,2511,Wheat and products,5611,Import Quantity,1000 tonnes,7461.00,8531.00,8255.00,8105.00,8434.00
29,4,Algeria,2511,Wheat and products,5072,Stock Variation,1000 tonnes,487.00,1401.00,731.00,546.00,1927.00
...,...,...,...,...,...,...,...,...,...,...,...,...
60913,181,Zimbabwe,2928,Miscellaneous,5611,Import Quantity,1000 tonnes,42.00,47.00,34.00,15.00,16.00
60914,181,Zimbabwe,2928,Miscellaneous,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,-4.00,0.00
60915,181,Zimbabwe,2928,Miscellaneous,5911,Export Quantity,1000 tonnes,1.00,1.00,1.00,1.00,1.00
60916,181,Zimbabwe,2928,Miscellaneous,5301,Domestic supply quantity,1000 tonnes,41.00,46.00,33.00,19.00,16.00
60917,181,Zimbabwe,2928,Miscellaneous,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60918,181,Zimbabwe,2928,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60919,181,Zimbabwe,2928,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.34,1.09
60920,181,Zimbabwe,2928,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,2.00,1.00
60921,181,Zimbabwe,2928,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.05,0.04
60922,181,Zimbabwe,2928,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.02
60923,181,Zimbabwe,2680,Infant food,5611,Import Quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60924,181,Zimbabwe,2680,Infant food,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60925,181,Zimbabwe,2680,Infant food,5911,Export Quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60926,181,Zimbabwe,2680,Infant food,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60927,181,Zimbabwe,2680,Infant food,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60928,181,Zimbabwe,2680,Infant food,5142,Food,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60929,181,Zimbabwe,2680,Infant food,645,Food supply quantity (kg/capita/yr),kg,0.00,0.00,0.00,0.00,0.01
60930,181,Zimbabwe,2680,Infant food,664,Food supply (kcal/capita/day),kcal/capita/day,0.00,0.00,0.00,0.00,0.00
60931,181,Zimbabwe,2680,Infant food,674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
60932,181,Zimbabwe,2680,Infant food,684,Fat supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
60933,181,Zimbabwe,2899,Miscellaneous,5611,Import Quantity,1000 tonnes,42.00,47.00,33.00,15.00,16.00
60934,181,Zimbabwe,2899,Miscellaneous,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,-4.00,0.00
60935,181,Zimbabwe,2899,Miscellaneous,5911,Export Quantity,1000 tonnes,1.00,1.00,0.00,0.00,1.00
60936,181,Zimbabwe,2899,Miscellaneous,5301,Domestic supply quantity,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60937,181,Zimbabwe,2899,Miscellaneous,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [50]:
df.groupby('Area')['Y2017'].sum()

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
Côte d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                          21267.96
Liberia                          29342.20
Madagascar                      131197.73
Malawi                          181098.71
Mali                            149928.33
Mauritania                      156665.46
Mauritius                        51114.83
Morocco                         388495.36
Mozambique                      161407.98
Namibia                          29874.89
Niger                           126707.58
Nigeria                        1483268.23
Rwanda                           73663.69
Sao Tome and Principe            12662.63
Senegal                          95681.15
Seychelles                         442.34
Sierra Leone                     55311.33
South Africa                    517590.54
Sudan                           239931.92
Sudan (former)                       0.00
Togo                             49841.88
Tunisia                         124167.20
Uganda                          213950.38
United Republic of Tanzania     322616.85
Zambia                          103223.77
Zimbabwe                         75919.34
Name: Y2017, dtype: float64

In [6]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [7]:
df[['Area']].count()

Area    60943
dtype: int64

In [12]:
#df.groupby('Element Code')['Y2017'].corrcoef()

In [16]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

In [13]:
S = [['him', 'sell'], [90, 28, 43]]

In [14]:
S[0][1][1]

'e'

In [53]:
df.groupby('Element').first()

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,4,Algeria,2501,Population,5301,1000 tonnes,0.00,0.00,0.00,0.00,0.00
Export Quantity,4,Algeria,2905,Cereals - Excluding Beer,5911,1000 tonnes,3.00,7.00,7.00,10.00,17.00
Fat supply quantity (g/capita/day),4,Algeria,2901,Grand Total,684,g/capita/day,80.06,79.36,77.40,80.19,77.28
Feed,4,Algeria,2905,Cereals - Excluding Beer,5521,1000 tonnes,4725.00,5070.00,4838.00,4667.00,5266.00
Food,4,Algeria,2905,Cereals - Excluding Beer,5142,1000 tonnes,8546.00,8729.00,9001.00,8941.00,9219.00
Food supply (kcal/capita/day),4,Algeria,2901,Grand Total,664,kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
Food supply quantity (kg/capita/yr),4,Algeria,2905,Cereals - Excluding Beer,645,kg,219.56,219.72,221.98,216.02,218.31
Import Quantity,4,Algeria,2905,Cereals - Excluding Beer,5611,1000 tonnes,12604.00,13983.00,13523.00,13039.00,13182.00
Losses,4,Algeria,2905,Cereals - Excluding Beer,5123,1000 tonnes,1084.00,1203.00,1148.00,1121.00,1253.00
Other uses (non-food),4,Algeria,2905,Cereals - Excluding Beer,5154,1000 tonnes,787.00,847.00,835.00,840.00,951.00
Processing,4,Algeria,2905,Cereals - Excluding Beer,5131,1000 tonnes,35.00,38.00,37.00,33.00,44.00
Production,4,Algeria,2905,Cereals - Excluding Beer,5511,1000 tonnes,3436.00,3761.00,3445.00,3478.00,6065.00
Protein supply quantity (g/capita/day),4,Algeria,2901,Grand Total,674,g/capita/day,94.90,94.35,94.72,92.82,91.83
Residuals,4,Algeria,2905,Cereals - Excluding Beer,5170,1000 tonnes,0.00,0.00,0.00,0.00,-8.00
Seed,4,Algeria,2905,Cereals - Excluding Beer,5527,1000 tonnes,177.00,189.00,197.00,202.00,278.00
Stock Variation,4,Algeria,2905,Cereals - Excluding Beer,5072,1000 tonnes,684.00,1663.00,905.00,705.00,2226.00
Total Population - Both sexes,4,Algeria,2501,Population,511,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
Tourist consumption,7,Angola,2913,Oilcrops,5171,1000 tonnes,0.00,0.00,0.00,0.00,0.00

In [19]:
y = [(2, 4), (7, 8), (1, 5, 9)]
y

[(2, 4), (7, 8), (1, 5, 9)]

In [20]:
y[1][-1]

8

In [31]:
lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = ['Age','Nationality','Overall']

In [38]:
#pd.DataFrame(lst,columns=['Age','Nationality','Overaall',index=[1,2,3])

In [39]:
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [54]:
df.groupby('Element')['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [55]:
df.groupby('Element')['Y2015'].sum()

Element
Domestic supply quantity                  2021493.55
Export Quantity                            157614.47
Fat supply quantity (g/capita/day)          10235.74
Feed                                       225050.22
Food                                      1232361.10
Food supply (kcal/capita/day)              453383.00
Food supply quantity (kg/capita/yr)         49345.13
Import Quantity                            267018.46
Losses                                     155439.00
Other uses (non-food)                       66254.41
Processing                                 287929.00
Production                                1947019.39
Protein supply quantity (g/capita/day)      11833.95
Residuals                                   30045.00
Seed                                        23976.82
Stock Variation                             34910.99
Total Population - Both sexes             1058081.00
Tourist consumption                           349.00
Name: Y2015, dtype: float64